server:
  port: 8089

spring:
  application:
    name: aheadshop-distribution
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/aheadshop_distribution?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai
    username: root
    password: 1551974285
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
  config:
    import: nacos:aheadshop-distribution.yml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# 佣金配置
commission:
  default-rate: 0.1000
  freeze-days: 1
  min-withdraw-amount: 100.00

logging:
  level:
    com.aheadshop.distribution: debug
