server:
  port: 8083

spring:
  application:
    name: aheadshop-cart
  config:
    import: nacos:aheadshop-cart.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456

knife4j:
  enable: true
  openapi:
    title: 购物车服务接口
    description: "购物车"
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.aheadshop.cart.controller
