server:
  port: 8081
spring:
  application:
    name: aheadshop-user
  config:
    import: nacos:aheadshop-user.yml
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        namespace: public
      config:
        server-addr: 127.0.0.1:8848
        namespace: public
        group: DEFAULT_GROUP
        file-extension: yaml
  data:
    redis:
      host: 127.0.0.1
      port: 6379
      database: 0
      password: 123456
  datasource:
    url: jdbc:mysql://localhost:3306/aheadshop_user?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1551974285
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 5MB

# 头像上传配置
upload:
  avatar-path: D:/Intelli J IDEA/IDEA 项目/aheadshop-plus/upload/avatar/
  avatar-url-prefix: http://localhost:8081/avatar/



mybatis-plus:
  configuration:
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      update-strategy: not_null
      id-type: auto

feign:
  okhttp:
    enabled: true # 开启OKHttp功能

knife4j:
  enable: true
  openapi:
    title: 用户服务相关的接口
    description: "用户"
    email: 1551974285@qq.com
    concat: 枫溪
    version: v1.0.0
    group:
      default:
        group-name: default
        api-rule: package
        api-rule-resources:
          - com.aheadshop.user.controller
